#!/usr/bin/env zsh
(( ${path[(I)/usr/local/bin]} )) || path=( /usr/local/bin $path )
(( ${fpath[(I)/usr/local/share/zsh/site-functions]} )) || fpath=( /usr/local/share/zsh/site-functions $fpath )
(( ${fpath[(I)/usr/local/share/zsh-completions]} )) || fpath=( /usr/local/share/zsh-completions $fpath )

export PATH
export FPATH
