#!/usr/bin/env zsh

() {
  _bootstrap_link "${_bootstrap_components}/neovim" "$HOME/.config/nvim"
  _log "> Syncing neovim plugins"
  nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
} "$@"
